graph TB;
Program --> DebugConsole;
Program --> Game;
Game --> World;
World --> Components;
Components --> GeneralComponents;
Components --> CustomComponents;
GeneralComponents --> TransformComponent --> ComponentCollection;
GeneralComponents --> RigitBodyComponent --> ComponentCollection;
GeneralComponents --> ForcesComponent --> ComponentCollection;
GeneralComponents --> SDFRenderComponent --> ComponentCollection;
GeneralComponents --> SDFColliderComponent --> ComponentCollection;
GeneralComponents --> SphereColliderComponent --> ComponentCollection;
GeneralComponents --> InputComponent --> ComponentCollection;
GeneralComponents --> WorldSDFRendererComponent --> ComponentCollection;
GeneralComponents --> WorldSDFColliderComponent --> ComponentCollection;
GeneralComponents --> WorldGravityPlaneComponent --> ComponentCollection;
GeneralComponents --> GlobalRenderParamComponent --> ComponentCollection;
GeneralComponents --> GlobalPhysicsParamComponent --> ComponentCollection;
GeneralComponents --> CameraComponent --> ComponentCollection;
CustomComponents --> GameStatusComponent --> ComponentCollection;
CustomComponents --> BallControlComponent --> ComponentCollection;
World --> Entities;
Entities --> Player --> EntitiesCollection;
Entities --> Objects --> EntitiesCollection;
Entities --> Camera --> EntitiesCollection;
Entities --> ComponentCollection;
World --> Systems;
Systems --> GeneralSystems;
Systems --> CustomSystems;
GeneralSystems --> GravitationSystem --> SystemCollection;
GeneralSystems --> TransformUpdateSystem --> SystemCollection;
GeneralSystems --> RigidBodyUpdateSystem --> SystemCollection;
GeneralSystems --> BuildWorldSDFColliderSystem --> SystemCollection;
GeneralSystems --> SphereCollisionTestingSystem --> SystemCollection;
GeneralSystems --> ResetWorldSDFColliderSystem --> SystemCollection;
GeneralSystems --> WorldSDFRenderingSystem --> SystemCollection;
GeneralSystems --> InputSystem --> SystemCollection;
CustomSystems --> PlayerUpdateSystem --> SystemCollection;
SystemCollection --> ComponentCollection;
WorldSDFRenderingSystem --> WebGLRenderer;
WebGLRenderer --> EntitiesCollection;
WebGLRenderer --> Scene;
Scene --> Lights;
Lights --> Sun[Sun<br>not used];
Scene --> Skybox;
Scene --> sceneObjectDict;
sceneObjectDict --> GObject-1[GObject-1<br>GSDFObject];
sceneObjectDict --> GObject-2[GObject-2<br>GSDFObject];
GObject-1 --> Material-1[GSDFWorld];
GObject-1 --> Buffer1..[Buffer1..<br>VertexBuffer1<br>IndexBuffer1];
GObject-2 --> Buffer2..;
GObject-2 --> Material-2[GSDFBox];
Material-1 --> RenderType-1[RenderType-1<br>Program-1];
Material-2 --> RenderType-2[RenderType-2<br>Program-2];
RenderType-1 --> FragmentShader-A[SDF_WORLD.frag];
RenderType-1 --> VertexShader-A[SDF.vert];
RenderType-2 --> FragmentShader-B[NIL];
RenderType-2 --> VertexShader-A;
style RenderType-2 fill:lightgreen;
style RenderType-1 fill:lightgreen;
style FragmentShader-A fill:lightgreen;
style FragmentShader-B fill:lightgreen;
style VertexShader-A fill:lightgreen;
style VertexShader-A fill:lightgreen;
style Buffer1.. fill:yellow;
style Buffer2.. fill:yellow;
