graph TB;
Program --> DebugConsole;
Program --> Game;
Game --> WebGLRenderer;
Game --> Player;
Game --> SceneGenerator[SceneGenerator<br>not done yet];
SceneGenerator --> Scene;
Game --> Physics[Physics<br>not done yet];
Physics --> Player;
WebGLRenderer --> Scene;
Scene --> Lights;
Lights --> Sun[Sun<br>not used];
Scene --> Skybox;
Scene --> sceneObjectDict;
WebGLRenderer --> Camera;
Player --> Camera;
sceneObjectDict --> GObject-1[GObject-1<br>GSDFObject];
sceneObjectDict --> GObject-2[GObject-2<br>GSDFObject];
GObject-1 --> Material-1[GSDFWorld];
GObject-1 --> Buffer1..[Buffer1..<br>VertexBuffer1<br>IndexBuffer1];
GObject-2 --> Buffer2..;
GObject-2 --> Material-2[GSDFBox];
Material-1 --> RenderType-1[RenderType-1<br>Program-1];
Material-2 --> RenderType-2[RenderType-2<br>Program-2];
RenderType-1 --> FragmentShader-A[SDF_WORLD.frag];
RenderType-1 --> VertexShader-A[SDF.vert];
RenderType-2 --> FragmentShader-B[NIL];
RenderType-2 --> VertexShader-A;
style RenderType-2 fill:lightgreen;
style RenderType-1 fill:lightgreen;
style FragmentShader-A fill:lightgreen;
style FragmentShader-B fill:lightgreen;
style VertexShader-A fill:lightgreen;
style VertexShader-A fill:lightgreen;
style Buffer1.. fill:yellow;
style Buffer2.. fill:yellow;
