export const GENERAL_SIGNS = {
    "TRANSFORM": "TRANSFORM",
    "RIGIDBODY": "RIGIDBODY",
    "FORCES": "FORCES",
    "SDF_RENDER": "SDF_RENDER",
    "SDF_COLLIDER": "SDF_COLLIDER",
    "SPHERE_COLLIDER": "SPHERE_COLLIDER",
}
export const SINGLETON_SIGNS = {
    "INPUT": "INPUT",
    "CAMERA": "CAMERA",
    "GLOBAL_RENDER_PARAM": "GLOBAL_RENDER_PARAM",
    "GLOBAL_PHYSICS_PARAM": "GLOBAL_PHYSICS_PARAM",
    "WORLD_SDF_RENDERER": "WORLD_SDF_RENDERER",
    "WORLD_SDF_COLLIDER": "WORLD_SDF_COLLIDER",
    "WORLD_GRAVITY_TO_PLANE": "WORLD_GRAVITY_TO_PLANE",
    "BALL_CONTROL": "BALL_CONTROL",
    "GAME_STATUS": "GAME_STATUS",
}